import { motion } from 'framer-motion';
import { ArrowUpRight, Target, Eye, Users, BriefcaseBusiness, Percent, CalendarDays, CheckCircle2 } from 'lucide-react';
import PageHero from '../components/PageHero';
import Reveal from '../components/Reveal';
import SectionTitle from '../components/SectionTitle';
import { stats } from '../data/site';

export default function About(){return <>
<PageHero title="About Us" subtitle="Passionate About High Quality Service for Businesses" image="https://images.unsplash.com/photo-1748347084012-075796185d56?auto=format&fit=crop&w=1900&q=85"/>
<section className="section about-story"><div className="container story-grid"><Reveal><div className="story-number"><span>Since</span><strong>10+</strong><small>Years of Experience</small></div></Reveal><Reveal delay={.12}><span className="eyebrow">About Us</span><h2>Your Trusted Partner for Industrial Equipment, Cooling Systems, and Technical Services</h2><p>With a focus on durability and performance, the brand ensures that critical machinery and systems are maintained to the highest standards, reducing downtime and supporting long-term operational sustainability.</p><p>At the heart of every successful operation is reliability. We help organizations keep equipment working efficiently and make better technical decisions.</p><div className="story-points"><span><CheckCircle2/> Professional expertise</span><span><CheckCircle2/> Reliable service</span><span><CheckCircle2/> Quality equipment</span><span><CheckCircle2/> Customer-focused support</span></div></Reveal></div></section>
<section className="dark-stats"><div className="container dark-stats-grid">{stats.map((s,i)=>{const Icon=[CalendarDays,BriefcaseBusiness,Percent,Users][i%4];return <Reveal key={s.label} delay={i*.06}><div><Icon size={20}/><strong>{s.value}</strong><span>{s.label}</span></div></Reveal>})}</div></section>
<section id="sustainability" className="section principle-section"><div className="container principle-grid"><Reveal className="principle-visual"><span className="eyebrow light">Our Mission & Vision</span><h2>Discover The Core Principles That Guides Us</h2><div className="principle-line"/></Reveal><div className="principle-copy"><Reveal><div className="principle-card"><div><Target/></div><span>01</span><h3>Our Mission</h3><p>To provide dependable technical solutions, professional service and practical guidance that help businesses achieve their objectives.</p></div></Reveal><Reveal delay={.12}><div className="principle-card"><div><Eye/></div><span>02</span><h3>Our Vision</h3><p>To become a trusted technical partner known for quality, reliability, innovation and customer satisfaction.</p></div></Reveal></div></div></section>
<section className="section why-new"><div className="container"><SectionTitle eyebrow="WHY CHOOSE US" title="Built on skill, experience and precision."/><div className="why-grid-new">{['Professional expertise','Reliable service','Quality equipment','Customer-focused support'].map((x,i)=><Reveal key={x} delay={i*.07}><div><span>0{i+1}</span><CheckCircle2/><h3>{x}</h3><p>We combine practical experience and professional dialogue to help you choose the right solution for your operational needs.</p></div></Reveal>)}</div></div></section>
</>}
