import { useState } from 'react';
import { Mail, Phone, MapPin, Clock, Send, CheckCircle2 } from 'lucide-react';
import { motion } from 'framer-motion';
import PageHero from '../components/PageHero';
import { company } from '../data/site';

export default function Contact(){const [sent,setSent]=useState(false);return <>
<PageHero title="Contact Us" subtitle="Let's discuss your next technical requirement." image="https://images.unsplash.com/photo-1780417914804-883e7345d1ea?auto=format&fit=crop&w=1900&q=85"/>
<section className="section contact-page"><div className="container contact-page-grid"><motion.div initial={{opacity:0,x:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><span className="eyebrow">Let's talk</span><h2>Tell us what your operation needs.</h2><p>We don't just serve you; we serve you professionally. Send us the details and the CIMA Technical team can follow up.</p><div className="contact-info"><a href={`mailto:${company.email}`}><Mail/><span><small>Email</small>{company.email}</span></a><a href={`tel:${company.phone.replace(/\s/g,'')}`}><Phone/><span><small>Phone</small>{company.phone}</span></a><div><MapPin/><span><small>Office</small>{company.address}</span></div><div><Clock/><span><small>Hours</small>{company.hours}</span></div></div></motion.div><motion.form className="main-form" action={`https://formsubmit.co/${company.email}`} method="POST" onSubmit={()=>setSent(true)} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><input type="hidden" name="_subject" value="CIMA Technical contact enquiry"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_template" value="table"/><div className="form-heading"><span>01</span><h3>Project enquiry</h3></div><label>Full name<input name="name" required placeholder="Your full name"/></label><label>Email address<input name="email" type="email" required placeholder="you@example.com"/></label><label>Phone number<input name="phone" required placeholder="+234 ..."/></label><label>Service required<select name="service" required><option value="">Select a service</option><option>Heavy Duty Equipment</option><option>Cooling Systems</option><option>Supplies</option><option>Servicing / Refurbishing</option><option>General Contracts</option></select></label><label>Project details<textarea name="message" rows="6" required placeholder="Tell us about the work, equipment or support you need..."></textarea></label><button className="btn btn-red full" type="submit">Submit enquiry <Send size={16}/></button>{sent&&<p className="form-note"><CheckCircle2 size={15}/> Your enquiry has been submitted. If this is the first FormSubmit submission, confirm the email address when prompted by FormSubmit.</p>}</motion.form></div></section>
</>}
